### PR TITLE
Restructure project into workspace for better codebase separation

### PR DESCRIPTION
**Pull request by sandreae**
Restructure the code base in order to support GTK-free-development to occur in when it is not required. All of the backend networking logic (the p2panda bits) have been split out into their own library/crate. This allows us to use whichever IDE setup we prefer and enjoy our usual tooling during development there. Flatpak builder is still required when building/running the complete app of course.

Concretely the restructure involves:
- converting the project into a cargo workspace https://doc.rust-lang.org/book/ch14-03-cargo-workspaces.html
- introduce `aardvark-app` binary crate where all GTK development happens
- introduce `aardvark-node` lib crate where non-GTK development can happen (moved backend p2panda code there, could also move some of the automerge logic later)
- `aardvark-app` now depends on `aardvark-node` in it's `Cargo.toml` by `path`
- update meson build files in order to account for this new structure

To run build and run the app we still open the root directory in flatpak builder as is currently the case.

### CODE REVIEW

**Comment by adzialocha** [comment]
Looking good! I think more "idiomatic" way to name the folders would be with an underscore (`aardvark_app`), but that's a detail.

**Comment by sandreae** [comment]
> Looking good! I think more "idiomatic" way to name the folders would be with an underscore (`aardvark_app`), but that's a detail.

Yeh, I thought so too, but then went with [p2panda convention](https://github.com/p2panda/p2panda/tree/main) for consistency :sweat_smile:

**Comment by adzialocha** [comment]
> Yeh, I thought so too, but then went with [p2panda convention](https://github.com/p2panda/p2panda/tree/main) for consistency 😅

Sweet, that makes sense as well!

**Comment by swick** [comment]
Good to merge?

**Comment by bertob** [comment]
I'm not qualified to review this, but no objections :)

**Pull request merged**
